// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRecommendersParams creates a new GetRecommendersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRecommendersParams() *GetRecommendersParams {
	return &GetRecommendersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecommendersParamsWithTimeout creates a new GetRecommendersParams object
// with the ability to set a timeout on a request.
func NewGetRecommendersParamsWithTimeout(timeout time.Duration) *GetRecommendersParams {
	return &GetRecommendersParams{
		timeout: timeout,
	}
}

// NewGetRecommendersParamsWithContext creates a new GetRecommendersParams object
// with the ability to set a context for a request.
func NewGetRecommendersParamsWithContext(ctx context.Context) *GetRecommendersParams {
	return &GetRecommendersParams{
		Context: ctx,
	}
}

// NewGetRecommendersParamsWithHTTPClient creates a new GetRecommendersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRecommendersParamsWithHTTPClient(client *http.Client) *GetRecommendersParams {
	return &GetRecommendersParams{
		HTTPClient: client,
	}
}

/* GetRecommendersParams contains all the parameters to send to the API endpoint
   for the get recommenders operation.

   Typically these are written to a http.Request.
*/
type GetRecommendersParams struct {

	// SiteID.
	SiteID string

	// XCqClientID.
	XCqClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get recommenders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecommendersParams) WithDefaults() *GetRecommendersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get recommenders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecommendersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get recommenders params
func (o *GetRecommendersParams) WithTimeout(timeout time.Duration) *GetRecommendersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recommenders params
func (o *GetRecommendersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recommenders params
func (o *GetRecommendersParams) WithContext(ctx context.Context) *GetRecommendersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recommenders params
func (o *GetRecommendersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recommenders params
func (o *GetRecommendersParams) WithHTTPClient(client *http.Client) *GetRecommendersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recommenders params
func (o *GetRecommendersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteID adds the siteID to the get recommenders params
func (o *GetRecommendersParams) WithSiteID(siteID string) *GetRecommendersParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get recommenders params
func (o *GetRecommendersParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithXCqClientID adds the xCqClientID to the get recommenders params
func (o *GetRecommendersParams) WithXCqClientID(xCqClientID string) *GetRecommendersParams {
	o.SetXCqClientID(xCqClientID)
	return o
}

// SetXCqClientID adds the xCqClientId to the get recommenders params
func (o *GetRecommendersParams) SetXCqClientID(xCqClientID string) {
	o.XCqClientID = xCqClientID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecommendersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param siteId
	if err := r.SetPathParam("siteId", o.SiteID); err != nil {
		return err
	}

	// header param x-cq-client-id
	if err := r.SetHeaderParam("x-cq-client-id", o.XCqClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
