// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSendViewRecoParams creates a new SendViewRecoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendViewRecoParams() *SendViewRecoParams {
	return &SendViewRecoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendViewRecoParamsWithTimeout creates a new SendViewRecoParams object
// with the ability to set a timeout on a request.
func NewSendViewRecoParamsWithTimeout(timeout time.Duration) *SendViewRecoParams {
	return &SendViewRecoParams{
		timeout: timeout,
	}
}

// NewSendViewRecoParamsWithContext creates a new SendViewRecoParams object
// with the ability to set a context for a request.
func NewSendViewRecoParamsWithContext(ctx context.Context) *SendViewRecoParams {
	return &SendViewRecoParams{
		Context: ctx,
	}
}

// NewSendViewRecoParamsWithHTTPClient creates a new SendViewRecoParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendViewRecoParamsWithHTTPClient(client *http.Client) *SendViewRecoParams {
	return &SendViewRecoParams{
		HTTPClient: client,
	}
}

/* SendViewRecoParams contains all the parameters to send to the API endpoint
   for the send view reco operation.

   Typically these are written to a http.Request.
*/
type SendViewRecoParams struct {

	// Body.
	Body SendViewRecoBody

	// SiteID.
	SiteID string

	// XCqClientID.
	XCqClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send view reco params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendViewRecoParams) WithDefaults() *SendViewRecoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send view reco params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendViewRecoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send view reco params
func (o *SendViewRecoParams) WithTimeout(timeout time.Duration) *SendViewRecoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send view reco params
func (o *SendViewRecoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send view reco params
func (o *SendViewRecoParams) WithContext(ctx context.Context) *SendViewRecoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send view reco params
func (o *SendViewRecoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send view reco params
func (o *SendViewRecoParams) WithHTTPClient(client *http.Client) *SendViewRecoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send view reco params
func (o *SendViewRecoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send view reco params
func (o *SendViewRecoParams) WithBody(body SendViewRecoBody) *SendViewRecoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send view reco params
func (o *SendViewRecoParams) SetBody(body SendViewRecoBody) {
	o.Body = body
}

// WithSiteID adds the siteID to the send view reco params
func (o *SendViewRecoParams) WithSiteID(siteID string) *SendViewRecoParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the send view reco params
func (o *SendViewRecoParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithXCqClientID adds the xCqClientID to the send view reco params
func (o *SendViewRecoParams) WithXCqClientID(xCqClientID string) *SendViewRecoParams {
	o.SetXCqClientID(xCqClientID)
	return o
}

// SetXCqClientID adds the xCqClientId to the send view reco params
func (o *SendViewRecoParams) SetXCqClientID(xCqClientID string) {
	o.XCqClientID = xCqClientID
}

// WriteToRequest writes these params to a swagger request
func (o *SendViewRecoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param siteId
	if err := r.SetPathParam("siteId", o.SiteID); err != nil {
		return err
	}

	// header param x-cq-client-id
	if err := r.SetHeaderParam("x-cq-client-id", o.XCqClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
