// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSendAddToCartParams creates a new SendAddToCartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendAddToCartParams() *SendAddToCartParams {
	return &SendAddToCartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendAddToCartParamsWithTimeout creates a new SendAddToCartParams object
// with the ability to set a timeout on a request.
func NewSendAddToCartParamsWithTimeout(timeout time.Duration) *SendAddToCartParams {
	return &SendAddToCartParams{
		timeout: timeout,
	}
}

// NewSendAddToCartParamsWithContext creates a new SendAddToCartParams object
// with the ability to set a context for a request.
func NewSendAddToCartParamsWithContext(ctx context.Context) *SendAddToCartParams {
	return &SendAddToCartParams{
		Context: ctx,
	}
}

// NewSendAddToCartParamsWithHTTPClient creates a new SendAddToCartParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendAddToCartParamsWithHTTPClient(client *http.Client) *SendAddToCartParams {
	return &SendAddToCartParams{
		HTTPClient: client,
	}
}

/* SendAddToCartParams contains all the parameters to send to the API endpoint
   for the send add to cart operation.

   Typically these are written to a http.Request.
*/
type SendAddToCartParams struct {

	// Body.
	Body SendAddToCartBody

	// SiteID.
	SiteID string

	// XCqClientID.
	XCqClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send add to cart params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendAddToCartParams) WithDefaults() *SendAddToCartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send add to cart params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendAddToCartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send add to cart params
func (o *SendAddToCartParams) WithTimeout(timeout time.Duration) *SendAddToCartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send add to cart params
func (o *SendAddToCartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send add to cart params
func (o *SendAddToCartParams) WithContext(ctx context.Context) *SendAddToCartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send add to cart params
func (o *SendAddToCartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send add to cart params
func (o *SendAddToCartParams) WithHTTPClient(client *http.Client) *SendAddToCartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send add to cart params
func (o *SendAddToCartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send add to cart params
func (o *SendAddToCartParams) WithBody(body SendAddToCartBody) *SendAddToCartParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send add to cart params
func (o *SendAddToCartParams) SetBody(body SendAddToCartBody) {
	o.Body = body
}

// WithSiteID adds the siteID to the send add to cart params
func (o *SendAddToCartParams) WithSiteID(siteID string) *SendAddToCartParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the send add to cart params
func (o *SendAddToCartParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithXCqClientID adds the xCqClientID to the send add to cart params
func (o *SendAddToCartParams) WithXCqClientID(xCqClientID string) *SendAddToCartParams {
	o.SetXCqClientID(xCqClientID)
	return o
}

// SetXCqClientID adds the xCqClientId to the send add to cart params
func (o *SendAddToCartParams) SetXCqClientID(xCqClientID string) {
	o.XCqClientID = xCqClientID
}

// WriteToRequest writes these params to a swagger request
func (o *SendAddToCartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param siteId
	if err := r.SetPathParam("siteId", o.SiteID); err != nil {
		return err
	}

	// header param x-cq-client-id
	if err := r.SetHeaderParam("x-cq-client-id", o.XCqClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
