// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSendClickRecoParams creates a new SendClickRecoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendClickRecoParams() *SendClickRecoParams {
	return &SendClickRecoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendClickRecoParamsWithTimeout creates a new SendClickRecoParams object
// with the ability to set a timeout on a request.
func NewSendClickRecoParamsWithTimeout(timeout time.Duration) *SendClickRecoParams {
	return &SendClickRecoParams{
		timeout: timeout,
	}
}

// NewSendClickRecoParamsWithContext creates a new SendClickRecoParams object
// with the ability to set a context for a request.
func NewSendClickRecoParamsWithContext(ctx context.Context) *SendClickRecoParams {
	return &SendClickRecoParams{
		Context: ctx,
	}
}

// NewSendClickRecoParamsWithHTTPClient creates a new SendClickRecoParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendClickRecoParamsWithHTTPClient(client *http.Client) *SendClickRecoParams {
	return &SendClickRecoParams{
		HTTPClient: client,
	}
}

/* SendClickRecoParams contains all the parameters to send to the API endpoint
   for the send click reco operation.

   Typically these are written to a http.Request.
*/
type SendClickRecoParams struct {

	// Body.
	Body SendClickRecoBody

	// SiteID.
	SiteID string

	// XCqClientID.
	XCqClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send click reco params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendClickRecoParams) WithDefaults() *SendClickRecoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send click reco params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendClickRecoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send click reco params
func (o *SendClickRecoParams) WithTimeout(timeout time.Duration) *SendClickRecoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send click reco params
func (o *SendClickRecoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send click reco params
func (o *SendClickRecoParams) WithContext(ctx context.Context) *SendClickRecoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send click reco params
func (o *SendClickRecoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send click reco params
func (o *SendClickRecoParams) WithHTTPClient(client *http.Client) *SendClickRecoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send click reco params
func (o *SendClickRecoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send click reco params
func (o *SendClickRecoParams) WithBody(body SendClickRecoBody) *SendClickRecoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send click reco params
func (o *SendClickRecoParams) SetBody(body SendClickRecoBody) {
	o.Body = body
}

// WithSiteID adds the siteID to the send click reco params
func (o *SendClickRecoParams) WithSiteID(siteID string) *SendClickRecoParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the send click reco params
func (o *SendClickRecoParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithXCqClientID adds the xCqClientID to the send click reco params
func (o *SendClickRecoParams) WithXCqClientID(xCqClientID string) *SendClickRecoParams {
	o.SetXCqClientID(xCqClientID)
	return o
}

// SetXCqClientID adds the xCqClientId to the send click reco params
func (o *SendClickRecoParams) SetXCqClientID(xCqClientID string) {
	o.XCqClientID = xCqClientID
}

// WriteToRequest writes these params to a swagger request
func (o *SendClickRecoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param siteId
	if err := r.SetPathParam("siteId", o.SiteID); err != nil {
		return err
	}

	// header param x-cq-client-id
	if err := r.SetHeaderParam("x-cq-client-id", o.XCqClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
