// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ClientUserAgentParam User agent of the end user. Use if you're sending activities server-side for a client application.
//
// swagger:model ClientUserAgentParam
type ClientUserAgentParam string

// Validate validates this client user agent param
func (m ClientUserAgentParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this client user agent param based on context it is used
func (m ClientUserAgentParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
