// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ClientIDParam To use the Einstein API, you must pass the `x-cq-client-id` header with your Commerce Cloud Account Manager API Client ID.
// You can find this value in Business Manager, under Administration > Site Development > Open Commerce API Settings.
// This screen has a JSON object with all of your OCAPI configuration.
// You can use any of the values in a `client_id` field, but ideally you should create one specifically for Einstein API calls.
//
//
// swagger:model ClientIdParam
type ClientIDParam string

// Validate validates this client Id param
func (m ClientIDParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this client Id param based on context it is used
func (m ClientIDParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
