// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CookieIDParam Unique identifier of an anonymous shopper.
// **If you're making API requests from a traditional Commerce Cloud storefront, pass the `dwanonymous_*` cookie value
// (See [Browser-Based Local Data Storage](https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FDataProtectionAndPrivacy%2FLocalDataStorage.html&resultof=%22%64%77%61%6e%6f%6e%79%6d%6f%75%73%22%20%22%64%77%61%6e%6f%6e%79%6d%22%20) for more information).**
//
//
// swagger:model CookieIdParam
type CookieIDParam string

// Validate validates this cookie Id param
func (m CookieIDParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cookie Id param based on context it is used
func (m CookieIDParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
