// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// EinsteinSiteIDParam Your Einstein site ID, which can be found in the top right of the page on [Einstein Configurator](https://configurator.cquotient.com). It has the format `xxxx-<Commerce Cloud Site ID>`
//
// swagger:model EinsteinSiteIdParam
type EinsteinSiteIDParam string

// Validate validates this einstein site Id param
func (m EinsteinSiteIDParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this einstein site Id param based on context it is used
func (m EinsteinSiteIDParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
