// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RealmParam A unique four-character ID that you can get from your Account Executive (AE) or Customer Success Manager (CSM).
// Typically, the realm is the first four characters of the Einstein Site ID;
// but if your site changes realms in Commerce Cloud, the Einstein Site ID no longer contains the correct realm.
//
//
// swagger:model RealmParam
type RealmParam string

// Validate validates this realm param
func (m RealmParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this realm param based on context it is used
func (m RealmParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
