// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Recommender recommender
//
// swagger:model Recommender
type Recommender struct {

	// The description of the recommender.
	// Example: Recently viewed products.
	Description string `json:"description,omitempty"`

	// The name of the recommender.
	// Example: recently-viewed-products
	// Required: true
	Name *string `json:"name"`

	// The type of the recommender.
	// Example: recently-viewed
	// Required: true
	RecommenderType *string `json:"recommenderType"`
}

// Validate validates this recommender
func (m *Recommender) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecommenderType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Recommender) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Recommender) validateRecommenderType(formats strfmt.Registry) error {

	if err := validate.Required("recommenderType", "body", m.RecommenderType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this recommender based on context it is used
func (m *Recommender) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Recommender) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recommender) UnmarshalBinary(b []byte) error {
	var res Recommender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
