// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecommendationsResponse recommendations response
//
// swagger:model RecommendationsResponse
type RecommendationsResponse struct {

	// Identifier of this recommendation set.
	// Example: 05e0bd80-64eb-4149-ad5a-dfe1996f8f57
	// Required: true
	RecoUUID *string `json:"recoUUID"`

	// The set of recommendations.
	// Required: true
	Recs []*Recommendation `json:"recs"`
}

// Validate validates this recommendations response
func (m *RecommendationsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecoUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecommendationsResponse) validateRecoUUID(formats strfmt.Registry) error {

	if err := validate.Required("recoUUID", "body", m.RecoUUID); err != nil {
		return err
	}

	return nil
}

func (m *RecommendationsResponse) validateRecs(formats strfmt.Registry) error {

	if err := validate.Required("recs", "body", m.Recs); err != nil {
		return err
	}

	for i := 0; i < len(m.Recs); i++ {
		if swag.IsZero(m.Recs[i]) { // not required
			continue
		}

		if m.Recs[i] != nil {
			if err := m.Recs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this recommendations response based on the context it is used
func (m *RecommendationsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRecs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecommendationsResponse) contextValidateRecs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Recs); i++ {

		if m.Recs[i] != nil {
			if err := m.Recs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecommendationsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecommendationsResponse) UnmarshalBinary(b []byte) error {
	var res RecommendationsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
