// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecommendersResponse recommenders response
//
// swagger:model RecommendersResponse
type RecommendersResponse struct {

	// The list of available recommenders.
	// Required: true
	Recommenders []*Recommender `json:"recommenders"`
}

// Validate validates this recommenders response
func (m *RecommendersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecommenders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecommendersResponse) validateRecommenders(formats strfmt.Registry) error {

	if err := validate.Required("recommenders", "body", m.Recommenders); err != nil {
		return err
	}

	for i := 0; i < len(m.Recommenders); i++ {
		if swag.IsZero(m.Recommenders[i]) { // not required
			continue
		}

		if m.Recommenders[i] != nil {
			if err := m.Recommenders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recommenders" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recommenders" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this recommenders response based on the context it is used
func (m *RecommendersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRecommenders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecommendersResponse) contextValidateRecommenders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Recommenders); i++ {

		if m.Recommenders[i] != nil {
			if err := m.Recommenders[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recommenders" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recommenders" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecommendersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecommendersResponse) UnmarshalBinary(b []byte) error {
	var res RecommendersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
