// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// UserIDParam Application-provided unique identifier for logged in users (hashed).
//
// swagger:model UserIdParam
type UserIDParam string

// Validate validates this user Id param
func (m UserIDParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user Id param based on context it is used
func (m UserIDParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
