// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// UUIDParam Einstein API-provided unique identifier for the current user. This UUID is passed when available, and should only ever be populated with the last value returned in an activity response - never a client-generated value.
//
// swagger:model UuidParam
type UUIDParam string

// Validate validates this Uuid param
func (m UUIDParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Uuid param based on context it is used
func (m UUIDParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
